[2025-04-18T10:52:41.237085+02:00] app.ERROR: Uncaught Exception {"message":"No connection could be made because the target machine actively refused it","file":"C:\\xampp\\htdocs\\FYP\\FYP\\connect_db\\config.php","line":7,"trace":"#0 C:\\xampp\\htdocs\\FYP\\FYP\\connect_db\\config.php(7): mysqli->__construct('localhost', 'root', Object(SensitiveParameterValue), 'verosports')\n#1 C:\\xampp\\htdocs\\FYP\\FYP\\User\\app\\init.php(96): require_once('C:\\\\xampp\\\\htdocs...')\n#2 C:\\xampp\\htdocs\\FYP\\FYP\\User\\payment\\charge.php(6): require('C:\\\\xampp\\\\htdocs...')\n#3 {main}"} []
